### ISSUE TITLE
[Bug]: FastJEngine.getFPSData(FPSValue.Current) returns 0.0

### ISSUE THREAD

**Issue by oliverbooth** [fastjengine/FastJ#218]
### What happened?

Calling `FastJEngine.getFPSData(FPSValue.Current)` returns 0.0

### How to Reproduce the Error

```java
@Override
public void update(FastJCanvas canvas) {
    System.out.println(FastJEngine.getFPSData(FPSValue.Current));
}
```

### FastJ Version

other (please specify below)

### Specific FastJ Version

1.6.0

### Relevant Exceptions/Log Output

```shell
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucasstarsz** [comment]
I'll look into the issue as soon as I can. Thank you for posting!

**Comment by lucasstarsz** [comment]
Heya, I've found the issue.

In the current implementation of FastJEngine, getting the current fps value always returns 0.0 for the first 100 seconds because fpsLogIndex (index accessor for the fps log array I have) is always 1 value ahead of the actual current fps. When the first 100 seconds of FPS have been logged, the value will then always be 100 seconds behind.

In short, there was an off-by-one array accessing issue. 😅
I'll go ahead and make the PR, and you should be able to properly see the fix in the next latest FastJ release 👍🏾
